/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.school;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import programming.school.framework.Utilities;

class FrameworkTest {
  @Test
  public void randomNumberTest() {
    for ( int i=0; i<1000; i++ ) {
      int rnd = Utilities.randomNumber(10);
      assertTrue(rnd>=0);
      assertTrue(rnd<10);
    }
  }
}
