/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.school;

import java.awt.Graphics;

import javax.swing.JFrame;
import javax.swing.JPanel;

public class DrawingContainer extends JPanel {

	private IDrawingInstructions drawingInstructions;
	
	public DrawingContainer(IDrawingInstructions instr) {
		this.drawingInstructions = instr;
	}
	
    public void drawPicture(Graphics g) {
    	drawingInstructions.draw(g);
    }

    @Override
    public void paint(Graphics g) {
        drawPicture(g);
    }

    public void runContainer(String[] args) {
        JFrame f= new JFrame("Test");
        f.add(this);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        f.setSize(1000, 1000);
        f.setVisible(true);
    }

}
