/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.school.framework;

import java.awt.Graphics;

import javax.swing.JFrame;
import javax.swing.JPanel;

public class CoordinateSystem extends JPanel {

  private static final long serialVersionUID = 4150737648270389487L;

  private IMathPlotter plotter;
  private Graphics gr;

  public CoordinateSystem(IMathPlotter plotter) {
    this.plotter = plotter;
  }

  private int toXCoord(double x) {
    if (x < -1.0 || x > 1.0)
      throw new IllegalArgumentException("X coordinate can't be less than -1 or more than +1");
    return (int) Math.round(((double) plotter.maxX() * (x + 1.0)) / 2.0);
  }

  private int toYCoord(double y) {
    if (y < -1.0 || y > 1.0)
      throw new IllegalArgumentException("Y coordinate can't be less than -1 or more than +1");
    return (int) Math.round(((double) plotter.maxY() * (1.0 - y)) / 2.0);
  }

  @Override
  public void paint(final Graphics g) {
    g.drawLine(plotter.maxX() / 2, 0, plotter.maxX() / 2, plotter.maxY());
    g.drawLine(0, plotter.maxY() / 2, plotter.maxX(), plotter.maxY() / 2);

    g.drawString("(0,0)", plotter.maxX() / 2 + 2, plotter.maxY() / 2 - 2);
    g.drawString("(0,-1)", plotter.maxX() / 2 + 2, plotter.maxY() - 2);
    g.drawString("(0,1)", plotter.maxX() / 2 + 2, 10);
    g.drawString("(-1,0)", 2, plotter.maxY() / 2 - 2);
    g.drawString("(1,0)", plotter.maxX() - 35, plotter.maxY() / 2 - 2);

    gr = g;
    plotter.plot(this);
  }

  public void runContainer() {
    runContainer(plotter.windowTitle(), plotter.maxX(), plotter.maxY());
  }

  public void line(double x0, double y0, double x1, double y1) {
    gr.drawLine(toXCoord(x0), toYCoord(y0), toXCoord(x1), toYCoord(y1));
  }

  public void dot(double x0, double y0) {
    gr.drawOval(toXCoord(x0) - 2, toYCoord(y0) - 2, 3, 3);
  }

  public void runContainer(String title, int x, int y) {
    JFrame f = new JFrame(title);
    f.add(this);
    f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    f.setSize(x, y + 25);
    f.setVisible(true);
  }

}
